### ISSUE TITLE
Match priority order

### ISSUE THREAD

**Issue by diminutivesloop** [eamodio/vscode-find-related#5]
It would be helpful if the list of related files corresponded to the order of the configured locators. For example I currently have the following rule for Angular spec files:
```json
{
    "pattern": "(.*)\\.(?:spec.ts)$",
    "locators": [
        "{$1.ts,$1.html,$1.scss}"
    ]
}
```
Since I placed the locator for the main component typescript file first in the locators list I would expect it to also appear first in the results list. However currently this order is ignored and I always see the template html file first in the list.

**Comment by eamodio** [comment]
@diminutivesloop So sorry for the incredibly long delay, but this is supported today, just not in the way you currently have it.

If you want to control the ordering, you'll need to separate the locators into different items in the array:

```json
{
    "pattern": "(.*)\\.(?:spec.ts)$",
    "locators": [
        "$1.ts", "$1.html", "$1.scss"
    ]
}
```

That should cause any `ts` files to be first, then `html`, and finally `scss`

The way you currently have it is more efficient as it is a single file system scan (using that glob pattern), but because of that order is not honored in the results -- they are ordered by how ever the file-system returns the results of the search.

**Comment by diminutivesloop** [comment]
Ok cool. That works perfectly. Thanks!
